CREATE DATABASE IF NOT EXISTS BD_ALUGUEL;
USE BD_ALUGUEL;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLI_ID        INT AUTO_INCREMENT PRIMARY KEY,
    CLI_NOME      VARCHAR(50) NOT NULL,
    CLI_CPF       VARCHAR(11) NOT NULL,
    CLI_EMAIL     VARCHAR(50) NOT NULL,
    CLI_TELEFONE  VARCHAR(9) NOT NULL
);
ALTER TABLE CLIENTE
MODIFY COLUMN CLI_CPF VARCHAR(11) NOT NULL UNIQUE;

CREATE TABLE IF NOT EXISTS PRODUTO(
	PRO_ID       	    INT AUTO_INCREMENT PRIMARY KEY,
    PRO_NOME      		VARCHAR(50) NOT NULL,
    PRO_DESCRICAO 		VARCHAR(500),
    PRO_PRECO     		DOUBLE NOT NULL,
    PRO_QTD_DISPONIVEL  INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALU_ID             INT AUTO_INCREMENT PRIMARY KEY,
    ALU_DATA_ALUGUEL   DATE NOT NULL,
    ALU_DATA_DEVOLUCAO DATE NOT NULL,
    ALU_VALOR_TOTAL    DOUBLE NOT NULL,
    FK_CLI_ID          INT,
    FOREIGN KEY (FK_CLI_ID) REFERENCES CLIENTE(CLI_ID)
);

CREATE TABLE IF NOT EXISTS ALUGUEL_PRODUTO(
	ALP_ID  	INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	FK_PRO_ID	INT NOT NULL,
    FK_ALU_ID   INT NOT NULL,
    FOREIGN KEY (FK_PRO_ID) REFERENCES PRODUTO(PRO_ID),
    FOREIGN KEY (FK_ALU_ID) REFERENCES ALUGUEL(ALU_ID)
);

INSERT INTO CLIENTE(CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES             ("ANA", 12345678912, "ana@gmail.com",191234567);

INSERT INTO CLIENTE(CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES 			   ("PEDRO", 61563403005, "pedro@gmail.com",191234567);

SELECT * FROM CLIENTE;

INSERT INTO PRODUTO(PRO_NOME,PRO_PRECO,PRO_QTD_DISPONIVEL)
VALUES			  ("Iphone 18 pro max",589.90,100);

INSERT INTO PRODUTO(PRO_NOME,PRO_DESCRICAO,PRO_PRECO,PRO_QTD_DISPONIVEL)
VALUES			  ("Lancha Turbo", "lancha para rio e mar", 2358.75, 5);

SELECT * FROM PRODUTO;

INSERT INTO ALUGUEL (ALU_DATA_ALUGUEL,ALU_DATA_DEVOLUCAO,ALU_VALOR_TOTAL, FK_CLI_ID)
VALUES              ("2026-10-08","2026-10-15", 600.89, 2);

SELECT * FROM ALUGUEL;

INSERT INTO ALUGUEL_PRODUTO(FK_PRO_ID, FK_ALU_ID)
VALUE                      (1,1);

SELECT * FROM ALUGUEL_PRODUTO;

INSERT INTO CLIENTE(CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES             ("Ana Silva", 42573389030, "ana.silva@gmail.com", 192837475);

INSERT INTO CLIENTE(CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES             ("Bruno Souza", 90782193005, "bruno.souza@gmail.com", 123456789);

INSERT INTO CLIENTE(CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES             ("Carla Mendes", 53510227026, "carla.mendes@gmail.com", 949289835);

INSERT INTO CLIENTE(CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES             ("Daniel Rocha", 90782193005, "daniel.rocha@gmail.com", 901650893);

INSERT INTO CLIENTE(CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES             ("Elaine Costa", 42573389030, "elaine.costa@gmail.com", 859364575);

INSERT INTO CLIENTE(CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES             ("Felipe Lima", 90782193005, "felipe.lima@gmail.com", 519847887);

INSERT INTO CLIENTE(CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES             ("Giselle Martins", 45733574089, "giselle.martins@gmail.com", 984800732);

INSERT INTO CLIENTE(CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES             ("Henrique Alves", 43063878014, "henrique.alves@gmail.com", 859364575);

INSERT INTO CLIENTE(CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES             ("Isabela Ferreira", 06293336020, "isabela.ferreira@gmail.com", 179848007);

INSERT INTO CLIENTE(CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES             ("João Oliveira", 87841008007, "joao.oliveira@gmail.com", 949981437);

SELECT * FROM CLIENTE;

INSERT INTO PRODUTO(PRO_NOME,PRO_DESCRICAO,PRO_PRECO,PRO_QTD_DISPONIVEL)
VALUES			   ("Notebook dell inspiron", "notebook com processador intal cor i7, 16 gb de RAM, 512GB SSD", 450, 10),
				   ("Smartphone Sansung galaxy S21","Smartphone com tela de 6.2 polagadas, 128GB de armazenamento",350,15),
                   ("TV LG 55'' 4K", "Smart TV com resolução 4K e HDR", 280, 8),
                   ("Drone DJI Phantom 4","Drone com câmera 4K e estabilização de imagem",300,55),
                   ("Câm. Canon EOSI T7","Câmera DSLR com lente 18-55mm,24.1MP",250,2),
                   ("Camera goPro Hero 9","Câmera de ação com resolução 5K e resistência à água",80,60),
                   ("Tenda de eventos 5x5m","Tenda resistente á água e fácil de montar",200,4),
                   ("Microfone Shure SM58","Microfone para apresentações e shows",40,35),
                   ("Mesa de som Behring","Mesa de som com 16 canais e efeitos integrados",500,3),
                   ("Kit de iluminação fotográfica","Kit com coftbox, tripés e lâmpadas de LED",100,6);

SELECT *FROM PRODUTO;
SELECT PRO_NOME, PRO_DESCRICAO FROM PRODUTO;
SELECT PRO_NOME, PRO_DESCRICAO, PRO_PRECO FROM PRODUTO;

-- SELECIONAR APENAS OS PRODUTOS COM O PREÇO MAIOR QUE 250
SELECT * FROM PRODUTO WHERE PRO_PRECO > 250;

-- SELECIONAR APENAS O PRODUTO DE ID = 3
SELECT PRO_ID,PRO_NOME FROM PRODUTO WHERE PRO_ID = 3;

-- SELECIONAR TODOS OS PRODUTOS QUE CONTENHAM NOTEBOOK EM QUALQUER PARTE DO NOME
SELECT * FROM PRODUTO WHERE PRO_NOME LIKE '%NOTEBOOK%';

-- ATUALIZAR A QUANTIDADE DE NOTEBOOK PARA 200
UPDATE PRODUTO SET PRO_QTD_DISPONIVEL = 200
WHERE PRO_ID=3; -- UPDATE TEM QUE TER WHERE

-- ATUALIZAR A DESCRIÇÃO DO NOTEBOOOK PARA VAZIO
UPDATE PRODUTO SET PRO_DESCRICAO= NULL
WHERE PRO_ID = 3;

-- APAGAR DELATAR O NOTEBOOK 
DELETE FROM PRODUTO 
WHERE PRO_ID = 3;



                   
				


