CREATE DATABASE IF NOT EXISTS BD_EST_MERCADO;
USE BD_EST_MERCADO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    TIPO VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(255) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	CODIGO_BARRAS VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PRECO VARCHAR (255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
	VALIDADE DATE NOT NULL,
    QUANTIDADE INT DEFAULT(0) NOT NULL,
    PESO INT NOT NULL,
    FK_CATEGORIA_ID INT,
    FOREIGN KEY (FK_CATEGORIA_ID) REFERENCES CATEGORIA(ID)
);

CREATE TABLE IF NOT EXISTS PRODUTO_FORNECEDOR(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	FK_PRODUTO_CODIGO_BARRAS VARCHAR(20),
    FK_FORNECEDOR_CNPJ VARCHAR(255),
    FOREIGN KEY (FK_PRODUTO_CODIGO_BARRAS) REFERENCES PRODUTO(CODIGO_BARRAS),
    FOREIGN KEY (FK_FORNECEDOR_CNPJ) REFERENCES FORNECEDOR(CNPJ)
);


