CREATE DATABASE IF NOT EXISTS BD_MUSICA;
USE BD_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ESTILO_MUSICAL VARCHAR(255),
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INT PRIMARY KEY,
    MAIS_OUVIDAS VARCHAR(500),
    NOME VARCHAR(100) NOT NULL,
    RITIMO VARCHAR(100) NOT NULL,
    ESTILO VARCHAR(100)NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DURACAO TIMESTAMP  NOT NULL,
    CAPA BLOB,
    FK_ARTISTA_CPF VARCHAR(11),
    FOREIGN KEY (FK_ARTISTA_CPF) REFERENCES ARTISTA(CPF)
);

CREATE TABLE  IF NOT EXISTS FAIXA(
	ID INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    OUVINTES VARCHAR(255) NOT NULL,
    DURACAO TIME NOT NULL,
    LETRA VARCHAR(1000) NOT NULL,
    FK_ALBUM_ID INT,
    FK_GENERO_ID INT,
    FOREIGN KEY (FK_ALBUM_ID) REFERENCES ALBUM(ID),
    FOREIGN KEY (FK_GENERO_ID) REFERENCES GENERO(ID)
);


